"""Merge content/curriculum/*.json into assets/curriculum.js for the Practice app.

The Practice page loads curriculum data as a JS global (window.CURRICULUM)
instead of fetching JSON, so the site keeps working when opened from disk
(file:// blocks fetch). Run this after editing any curriculum file, then
rebuild the site:

    py scripts/build_curriculum.py
    py scripts/build_site.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CURRICULUM_DIR = ROOT / "content" / "curriculum"
OUT_PATH = ROOT / "assets" / "curriculum.js"


def validate(subject: dict, path: Path, problems: list[str]) -> None:
    for key in ("id", "title", "order", "lesson", "days"):
        if key not in subject:
            problems.append(f"{path.name}: missing '{key}'")
            return
    if len(subject["days"]) != 10:
        problems.append(f"{path.name}: expected 10 days, found {len(subject['days'])}")
    for i, day in enumerate(subject["days"], start=1):
        for key in ("focus", "review", "task", "check"):
            if key not in day:
                problems.append(f"{path.name} day {i}: missing '{key}'")
        task = day.get("task") or {}
        for key in ("do", "capture"):
            if not task.get(key):
                problems.append(f"{path.name} day {i}: task missing '{key}'")
        checks = day.get("check") or []
        if len(checks) != 3:
            problems.append(f"{path.name} day {i}: expected 3 check questions, found {len(checks)}")
        for j, q in enumerate(checks, start=1):
            if not q.get("q"):
                problems.append(f"{path.name} day {i} check {j}: missing 'q'")
            if not q.get("rubric"):
                problems.append(f"{path.name} day {i} check {j}: missing 'rubric'")
            if not q.get("exemplar"):
                problems.append(f"{path.name} day {i} check {j}: missing 'exemplar'")
            if q.get("choices") is not None:
                problems.append(f"{path.name} day {i} check {j}: remove MCQ 'choices' — checks are open-ended now")


def main() -> int:
    files = sorted(CURRICULUM_DIR.glob("*.json"))
    if not files:
        print(f"No curriculum files found in {CURRICULUM_DIR}.")
        print("Generate them first (see inputs/agent-spec-curriculum-designer.md).")
        return 1

    subjects: list[dict] = []
    problems: list[str] = []
    for path in files:
        try:
            subject = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            problems.append(f"{path.name}: invalid JSON ({exc})")
            continue
        validate(subject, path, problems)
        subjects.append(subject)

    if problems:
        print("Curriculum validation failed:")
        for p in problems:
            print(f"  - {p}")
        return 1

    subjects.sort(key=lambda s: s["order"])
    goal_days = sum(len(s["days"]) for s in subjects)
    payload = {"goalDays": goal_days, "subjects": subjects}
    OUT_PATH.write_text(
        "// Generated by scripts/build_curriculum.py - do not edit by hand.\n"
        "window.CURRICULUM = "
        + json.dumps(payload, ensure_ascii=False)
        + ";\n",
        encoding="utf-8",
    )
    total_q = sum(len(d["check"]) for s in subjects for d in s["days"])
    print(f"Wrote {OUT_PATH.relative_to(ROOT)}: {len(subjects)} subjects, "
          f"{goal_days} days, {total_q} open-ended checks.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
